### PR TITLE
minor changes and comments

### PR DESCRIPTION
**Pull request by vaidik**

### CODE REVIEW

**Comment by vaidik** [comment]
* https://github.com/vishesh92/pg-admin#what-is-mvcc - probably link to an article explaining MVCC

**Comment by vaidik** [comment]
* https://github.com/vishesh92/pg-admin#list-users--roles - consider making this a table. it will be easier to read i think

**Comment by vaidik** [comment]
* https://github.com/vishesh92/pg-admin#rds-performance-insights - this section. how can we make it more useful?

**Comment by vaidik** [comment]
* Same problem here - https://github.com/vishesh92/pg-admin#grafana-dashboard

**Comment by vaidik** [comment]
Can you add something on how to decide which type of index to use?  - https://github.com/vishesh92/pg-admin#performance-tuning

**Comment by vaidik** [comment]
May be also add something on how to approach performance tuning - https://github.com/vishesh92/pg-admin/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R184.

especially for common workloads like transactions, high read, high write, insert/append only, etc.

**Comment by vaidik** [comment]
Can you add some real example here and have people walk through it? - https://github.com/vishesh92/pg-admin#identifying-common-issues-using-above

**Review by vishesh92 — APPROVED** [review]

**Pull request merged**
